### ISSUE TITLE
Runtime Error When Training in the ODETrainLoop (Connection Closed by Peer?...)

### ISSUE THREAD

**Issue by lchen64** [pantheon5100/pid_diffusion#2]
Hello,

If you have time, could you take a look at this issue I'm getting when running the distill_pid_diffusion.sh? I checked that my setup is correct. Thank you!

Traceback (most recent call last):
  File "/home/users/lchen64/lukechen/pid_diffusion/scripts/cm_train.py", line 189, in <module>
    main()
  File "/home/users/lchen64/lukechen/pid_diffusion/scripts/cm_train.py", line 130, in main
    ODETrainLoop(
  File "/home/users/lchen64/lukechen/pid_diffusion/cm/train_util.py", line 335, in __init__
    self._load_and_sync_teacher_parameters()
  File "/home/users/lchen64/lukechen/pid_diffusion/cm/train_util.py", line 375, in _load_and_sync_teacher_parameters
    dist_util.sync_params(self.teacher_model.parameters())
  File "/home/users/lchen64/lukechen/pid_diffusion/cm/dist_util.py", line 88, in sync_params
    dist.broadcast(p, 0)
  File "/home/users/lchen64/.conda/envs/pid-diffusion/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 1408, in broadcast
    work.wait()
RuntimeError: [/opt/conda/conda-bld/pytorch_1670525551200/work/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [10.0.1.17]:22780

**Comment by zebbsb** [comment]
hello, have you solved the question?
